"""add core tables

Revision ID: 9166cb937956
Revises: 
Create Date: 2026-09-28 20:00:31.835221+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9166cb937956'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('input_price_per_million', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('output_price_per_million', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('classifier_label', sa.String(length=20), nullable=False),
    sa.Column('classifier_reason', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_model_id'), 'requests', ['model_id'], unique=False)
    op.create_index(op.f('ix_requests_prompt_hash'), 'requests', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_requests_request_id'), 'requests', ['request_id'], unique=True)
    op.create_table('quality_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_scores_request_id'), 'quality_scores', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_scores_request_id'), table_name='quality_scores')
    op.drop_table('quality_scores')
    op.drop_index(op.f('ix_requests_request_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_prompt_hash'), table_name='requests')
    op.drop_index(op.f('ix_requests_model_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
